import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter",
});
const instrumentSans = Instrument_Serif({ weight: "400", subsets: ["latin"], variable: "--font-instrument-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <main className={`${instrumentSans.variable} ${inter.variable}`}>
        <body className="font-sans">
          <div className="w-full flex min-h-screen flex-col gap-8 items-center">
            <Navbar />
            <div className="w-full px-4 max-w-screen-sm flex-grow font-sans">{children}</div>
            <Footer />
          </div>
        </body>
      </main>
    </html>
  );
}
